# Generated by Django 5.0.6 on 2024-05-09 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('colour', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='bike images')),
            ],
        ),
        migrations.CreateModel(
            name='Specfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.CharField(choices=[('CRUISER', 'Cruiser'), ('Touring', 'Touring'), ('Chopper', 'Chopper'), ('Sports', 'Sports')], default='', max_length=50)),
                ('displacement', models.PositiveSmallIntegerField(help_text='Displacement in cc')),
                ('max_power', models.DecimalField(decimal_places=2, help_text='Maximum power in bhp', max_digits=5)),
                ('max_torque', models.DecimalField(decimal_places=2, help_text='Maximum torque in Nm', max_digits=5)),
                ('mileage_owner_reported', models.DecimalField(blank=True, decimal_places=2, help_text='Owner reported mileage in kmpl', max_digits=5, null=True)),
                ('transmission_type', models.CharField(help_text='Type of transmission e.g., Chain Drive', max_length=50)),
                ('transmission_gear_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of gears in the transmission', null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='website.bike')),
            ],
        ),
    ]
